version: "3.3"
services:
  postgres:
    container_name: cqrs
    image: postgres
    environment:
      POSTGRES_DB: "cqrs"
      POSTGRES_USER: "cqrs"
      POSTGRES_PASSWORD: "cqrs"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
