spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update  # create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs
    username: cqrs
    password: cqrs
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties: stringtype=unspecified
    tomcat:
      connection-properties: stringtype=unspecified
