###
POST http://localhost:8080/cqrs/cards
Content-Type: application/json

{
  "name": "name",
  "type": "type",
  "accountId": 1
}

###
GET http://localhost:8080/cqrs/cards/2

###
POST http://localhost:8080/cqrs/cards/2/updateName
Content-Type: application/json

{
  "name": "name2"
}
