GET http://localhost:8080/register/my_login

###
POST http://localhost:8080/register/my_login
Content-Type: application/json

{
  "password": "my_password"
}

###
DELETE http://localhost:8080/register/my_login
